scope: pg_cluster
namespace: /service/
name: "{{ hostname }}"

restapi:
    listen: "{{ hostname }}:8008"
    connect_address: "{{ hostname }}:8008"

etcd:
  hosts: 
    - "{{ node1_address }}:2379"
    - "{{ node2_address }}:2379"

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:

  initdb:
  - encoding: UTF8
  - data-checksums

  pg_hba:
  - host replication replicator 127.0.0.1/32 md5
  - host replication replicator "{{ node1_address }}"/0 md5
  - host replication replicator "{{ node2_address }}"/0 md5
  - host all all 0.0.0.0/0 md5

  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb

postgresql:
  listen: "{{ ansible_host }}:5432"
  connect_address: "{{ ansible_host }}:5432"
  data_dir: /var/lib/postgresql/13/main
  bin_dir: /usr/lib/postgresql/13/bin
  pgpass: /tmp/pgpass
  authentication:
    replication:
      username: replicator
      password: replicator
    superuser:
      username: {{ postgres_user }}
      password: {{ postgres_passwd }}

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false